
---
- hosts: dev

  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.8.0/

  roles:
    - role: candlepin

  vars:
    ansible_user: vagrant
    candlepin_git_pull: False
    candlepin_user: vagrant
    candlepin_user_home: /home/vagrant
    candlepin_checkout: /vagrant
