
---
- hosts: dev

  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.8.0/

  roles:
    - role: candlepin-root
      become: yes
      become_user: root
    - candlepin-user

  vars:
    ansible_user: vagrant
